### ISSUE TITLE
[1.10.2] Server crash if augmentStructures=true and RTG in use

### ISSUE THREAD

**Issue by UnixRonin** [gcewing/SGCraft#55]
I get a server crash on startup using SGCraft-1.13.2-mc1.10.2.jar if I enable AugmentStructures in an RTG world:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.3.239.jar)
  LMRECoremod ([1.9.4-1.10.x]LittleMaidReengaged-8.1.4.132.jar)
  CoreMod (TickProfiler-1.10.2.jenkins.31.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 2/13/18 11:06 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set it.unimi.dsi.fastutil.longs.Long2ObjectMap field net.minecraft.world.gen.structure.MapGenStructure.field_75053_d to gcewing.sg.SGStructureMap
        at gcewing.sg.BaseReflectionUtils.setField(BaseReflectionUtils.java:75)
        at gcewing.sg.FeatureGeneration.modifyScatteredFeatureGen(FeatureGeneration.java:53)
        at gcewing.sg.FeatureGeneration.onInitMapGen(FeatureGeneration.java:41)
        at gcewing.sg.SGCraft.onInitMapGen(SGCraft.java:259)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_SGCraft_onInitMapGen_InitMapGenEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
        at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:47)
        at rtg.world.gen.ChunkProviderRTG.<init>(ChunkProviderRTG.java:160)
        at rtg.world.WorldTypeRTG.getChunkGenerator(WorldTypeRTG.java:50)
        at net.minecraft.world.WorldProvider.func_186060_c(WorldProvider.java:61)
        at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:855)
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:115)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can not set it.unimi.dsi.fastutil.longs.Long2ObjectMap field net.minecraft.world.gen.structure.MapGenStructure.field_75053_d to gcewing.sg.SGStructureMap
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
        at gcewing.sg.BaseReflectionUtils.setField(BaseReflectionUtils.java:72)
        ... 16 more

The crash occurs **only** with augmentStructures=true.

**Comment by UnixRonin** [comment]
Sorry, just saw this is a duplicate of #43
